[package]
name = "query-pdb"
version = "0.1.0"
edition = "2021"

[dependencies]
binary-stream = "10.0.0"
binrw = "0.14.1"
bytemuck = { version = "1.21.0", features = ["derive"] }
pdb2 = "0.9.2"
serde = { version = "1.0.218", features = ["derive"] }
serde-binary = "0.5.0"
